language: rust
rust:
  - nightly
cache: cargo
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- rustup component add rustfmt-preview
script:
- cargo fmt --all -- --check
- cargo build
- cargo test