[package]
name = "simplewiki-rs"
version = "0.1.0"
authors = ["Sigurd Andreas Holsen <sighol@gmail.com>"]

[dependencies]
pulldown-cmark = "*"
rocket = "*"
rocket_codegen = "*"
rocket_contrib = { version = "*", features = ["handlebars_templates"] }
handlebars = "*"
regex = "*"

serde = "*"
serde_derive = "*"
serde_json = "*"
clap = "*"