[package]
name = "simplewiki-rs"
version = "0.1.0"
authors = ["Sigurd Andreas Holsen <sighol@gmail.com>"]

[dependencies]
pulldown-cmark = "*"
rocket = "~0.3.2"
rocket_codegen = "~0.3.2"
rocket_contrib = { version = "~0.3.2", features = ["handlebars_templates"] }
handlebars = "*"
regex = "*"

serde = "1.*"
serde_derive = "1.*"
serde_json = "1.*"
clap = "~2.26"