[package]
name = "simplewiki"
version = "0.8.1"
authors = ["Sigurd Andreas Holsen <sighol@gmail.com>"]

[dependencies]
pulldown-cmark = "*"
rocket = "^0.3.3"
rocket_codegen = "^0.3.3"
rocket_contrib = { version = "^0.3.3", features = ["handlebars_templates"] }
handlebars = "*"
regex = "*"

serde = "1.*"
serde_derive = "1.*"
serde_json = "1.*"
clap = "^2.26"

includedir = "0.2.2"
phf = "0.7.21"

# Open web browse on startup
open = "*"

# web socket that auto refreshes the wiki when the files change.
ws = "*"
spmc = "*"
notify = "*"

error-chain = "*"
walkdir = "*"

[build-dependencies]
includedir_codegen = "0.2.2"
